### ISSUE TITLE
Backing up files in storage folder

### ISSUE THREAD

**Issue by jove4015** [spatie/laravel-backup#353]
One of my main goals with this package was to backup user-generated content in the storage/app folder (in addition to the database and code backup, which is great).  I noticed that this path seems to be automatically excluded - I'm thinking maybe because the backup is also in this path?  Is there a way to include specific folders under storage/app that you want included in the backup?  I have a short list, I've tried explicitly including it in the "include" config and also creating a a listener for BackupManifestWasCreated and adding them there, but neither method seemed to result in my files winding up in the zip file.

**Comment by freekmurze** [comment]
The package will indeed automatically excluded any directory where the backup are stored in. Any other directory can be added to [`include`](https://github.com/spatie/laravel-backup/blob/d0b35fc/config/laravel-backup.php#L20) key in the config file.

It's kinda strange that adding directories to that key doesn't work for you. I haven't received any other issues regarding this. Maybe the problem is caused by something specific to your project.

Could you try installing the package in a vanilla Laravel app and try to backup some directories there?

**Comment by lasseal** [comment]
Having the same issue. Fresh install. Add files to `storage/app`. Add `storage/app` to the `include`key in the config. Run `php artisan backup:run --only-files`returns error `Backup failed because There are no files to be backed up.`

**Comment by freekmurze** [comment]
@lasseal I'll take a look at this soon

**Comment by freekmurze** [comment]
This has been fixed in `v4.3.3` of the package.

**Comment by lasseal** [comment]
* v4.4.3.

**Comment by freekmurze** [comment]
Thanks for the correction @lasseal !

**Comment by jove4015** [comment]
Awesome thank you guys!

**Comment by m7ammad7assan** [comment]
this issue still habbend to me also the size of generated zip is increased with the included files, but just DB backup i can see after extracting the zip file

**Comment by Muhammadn5** [comment]
> this issue still habbend to me also the size of generated zip is increased with the included files, but just DB backup i can see after extracting the zip file

How did you solved this issue???
